EXECUTABLES=Lab5

SRC=Lab5.c

OBJ=Lab5.o

CC=gcc

CFLAGS=-g

all: $(EXECUTABLES)

$(EXECUTABLES): $(SRC)
	
	$(CC) $(CFLAGS) -c $(SRC)

	$(CC) $(CFLAGS) -o $@ $(OBJ)

clean:
	rm -f $(EXECUTABLES) $(OBJ) *